version: "2"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - static_volume:/app/personal_site_static  # <-- bind the static volume
      - media_volume:/app/personal_site_media  # <-- bind the media volume
    env_file:
      - ./.prod
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '8002:8002'
    volumes:
      - static_volume:/app/personal_site_static  # <-- bind the static volume
      - media_volume:/app/personal_site_media  # <-- bind the media volume
    depends_on:
      - app

volumes:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume
